-- ════════════════════════════════════════════════════════════════════
-- El Lobo — Migración Supabase (turno en Egresos + clientes de fiado)
-- Ejecutar completo en: Supabase → SQL Editor → New query → Run
-- Es seguro volver a correrlo (usa IF NOT EXISTS)
-- ════════════════════════════════════════════════════════════════════

-- Columna nueva en "egresos" ---------------------------------------------
-- De qué turno es el gasto (almuerzo o comidas rápidas — 'cena' es el valor
-- interno que ya usa el resto de la app para comidas rápidas, ver
-- gastos_dia.turno). Nula/vacía si el gasto no aplica a un turno en
-- particular (arriendo, servicios, etc. — un gasto general del negocio).
alter table egresos add column if not exists turno text;
alter table egresos drop constraint if exists egresos_turno_check;
alter table egresos add constraint egresos_turno_check check (turno is null or turno in ('almuerzo','cena'));

-- Clientes de fiado --------------------------------------------------------
-- Base para asociar cada pedido "Fiar" a un cliente con nombre (antes era
-- anónimo — solo se sabía que había un fiado, no de quién). Sin RLS, igual
-- que el resto de las tablas de este proyecto.
create table if not exists clientes_fiado (
  id bigint generated by default as identity primary key,
  nombre text not null,
  telefono text,
  created_at timestamptz default now()
);

-- Columna nueva en "pedidos" ------------------------------------------------
-- A cuál cliente de clientes_fiado corresponde este pedido — solo tiene
-- valor cuando es_fiar=true; null en cualquier otro pedido.
alter table pedidos add column if not exists cliente_fiado_id bigint references clientes_fiado(id);

-- Refrescar el caché de esquema de PostgREST ------------------------------
-- Después de un ALTER TABLE/CREATE TABLE, la API de Supabase a veces tarda
-- en darse cuenta de los cambios y responde "Could not find the 'x' column
-- ... in the schema cache" aunque ya exista. Esta línea le avisa a PostgREST
-- que recargue el esquema de una vez, sin esperar el auto-refresco periódico.
notify pgrst, 'reload schema';
