-- ════════════════════════════════════════════════════════════════════
-- El Lobo — Migración Supabase (abonos de fiado — pagos parciales contra
-- el saldo TOTAL de un cliente, no contra un pedido puntual)
-- Ejecutar completo en: Supabase → SQL Editor → New query → Run
-- Es seguro volver a correrlo (usa IF NOT EXISTS)
-- ════════════════════════════════════════════════════════════════════

-- Tabla nueva "abonos_fiado" -----------------------------------------------
-- Un abono es plata que un cliente fiado entrega SIN que se sepa de
-- antemano contra cuál pedido/visita queda — se aplica automáticamente a
-- sus pedidos fiados pendientes, del más viejo al más nuevo (ver
-- registrarAbonoFiado() en el sistema). "cuenta" usa los mismos 2 valores
-- que ya usa pedidos.metodo (efectivo/transferencia) — no las 3 cuentas de
-- Caja, porque el abono termina repartido en pedidos con su propio turno
-- (almuerzo/cena), igual que cualquier otro pago de un pedido.
create table if not exists abonos_fiado (
  id bigint generated by default as identity primary key,
  cliente_fiado_id bigint not null references clientes_fiado(id),
  fecha date not null default current_date,
  monto numeric not null check (monto > 0),
  cuenta text not null default 'efectivo' check (cuenta in ('efectivo','transferencia')),
  nota text,
  created_at timestamptz default now()
);

-- Columna nueva en "pedidos" ------------------------------------------------
-- Marca los pedidos fiados que quedaron pagados AUTOMÁTICAMENTE al consumir
-- un abono (para no confundirlos con los que se pagan de una vez con el
-- botón normal) — se usa en la fórmula del saldo pendiente de cada cliente.
alter table pedidos add column if not exists pagado_via_abono boolean default false;

-- Refrescar el caché de esquema de PostgREST ------------------------------
-- Después de un CREATE TABLE/ALTER TABLE, la API de Supabase a veces tarda
-- en darse cuenta de los cambios y responde "Could not find the 'x' column
-- ... in the schema cache" aunque ya exista. Esta línea le avisa a PostgREST
-- que recargue el esquema de una vez, sin esperar el auto-refresco periódico.
notify pgrst, 'reload schema';
